/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "ib_constants.h"

namespace sharp { namespace api {

const ibConstants g_ib_constants;

ibConstants::ibConstants() {
}

}} // namespace

