/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ib_CONSTANTS_H
#define ib_CONSTANTS_H

#include "ib_types.h"

namespace sharp { namespace api {

class ibConstants {
 public:
  ibConstants();

};

extern const ibConstants g_ib_constants;

}} // namespace

#endif
